#!/bin/bash

prefix=THE_PREFIX

usage="\
Usage: libmtreefile-config  [--version] [--ldflags] [--cflags]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
            exit 1
	    fi

	    while test $# -gt 0; do

		      case $1 in
		          --prefix)
echo "$prefix"
;;
--cflags)
echo "-I$prefix/include"
;;
--ldflags)
echo "-L$prefix/lib -lmqtreefile -lzip "
;;
 *)
       echo "${usage}" 1>&2
             exit 1
	           ;;
		     esac
		       shift
		       done
		       



